# Generated by Django 2.0.1 on 2018-01-31 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=800000)),
                ('add_data', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(max_length=800000)),
                ('output_data', models.CharField(max_length=800000)),
                ('solution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_Solution', to='app.Solution')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(verbose_name='data published')),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='testResult_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_testResult', to='app.TestResult'),
        ),
    ]
