# Generated by Django 2.0.1 on 2018-02-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='solution_id',
        ),
    ]
