# Generated by Django 2.0.1 on 2018-02-01 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_test_solution_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='pub_time',
        ),
        migrations.AddField(
            model_name='solution',
            name='test_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_test', to='app.Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_name',
            field=models.CharField(default='12', max_length=30),
            preserve_default=False,
        ),
    ]
