# Generated by Django 2.0.1 on 2018-02-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180201_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='testResult_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testResult_id', to='app.TestResult'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_id', to='app.Test'),
        ),
    ]
